version: '3.8'

services:
  okey-server:
    image: okierummy-server:latest
    container_name: okey-server
    restart: always
    ports:
      - "8080:8080/udp"
    environment:
      - GODOT_HEADLESS=1
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
